[workspace]
members = [
    "ex_concepts",
    "ex_data_structures",
    "ex_ownership",  
    "ex_structs",
    "ex_enums_matching",
    "ex_nulls_errors",
    "ex_traits_generics",
    "inventory_manager",        
]
